#!/bin/sh

VALID_BRANCH_REGEX="(^(feature|fix|release|refactor))|^([A-Z]+\-[0-9]+)$"

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

if [[ "$BRANCH_NAME" =~ $VALID_BRANCH_REGEX ]]; then
  : nothing
else
  echo "Disallowed commits on branches that don't start with: feature, fix, release, refactor"
  echo "Current branch name: ${BRANCH_NAME}"
  exit 1;
fi

echo $(cat "$1") > "$1"
echo "" >> "$1"
echo "${BRANCH_NAME/"/"/: }" >> "$1"