#!/bin/sh

echo teste

# Regex to check the valid branch name
VALID_BRANCH_REGEX="(^(feature|fix|release|refactor))|^([A-Z]+\-[0-9]+)$"

# Get branch name and description
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

# check the branch name is valid or not
if [[ "$BRANCH_NAME" =~ $VALID_BRANCH_REGEX ]]; then
  : nothing
else
  echo "Branch Name not as per the defined rules like: feature, fix, release, refactor"
  echo "Current ${BRANCH_NAME}"
  exit 1;
fi

echo $(cat "$1") > "$1"
echo "" >> "$1"
echo "${BRANCH_NAME/"/"/: }" >> "$1"