name: Code review create on pull request opened

on:
  pull_request:
    types: [opened]

jobs:
  create-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Get work_item_id
        run: |
          echo "work_item_id=$(echo "$PULL_REQUEST_BODY" | grep "link_work_item" | grep -oE "[^/]+$" | awk '{print $1}' | tr -dc '0-9')" >> $GITHUB_ENV  
        env: 
          PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
      - name: Get iteration of work item
        run: |
          echo "current_iteration=$(curl --location --request GET 'https://dev.azure.com/brunodeuner/teste/_apis/wit/workitems/${{ env.work_item_id }}?api-version=7.0' \
            --header 'Authorization: Basic unbml4tuwcexawzao4zbqj37e6fwj7qjy4moa5iiazpjwvkfldqq' | jq '.fields."System.IterationPath"')" >> $GITHUB_ENV 
      - name: Create task 
        run: |          
          curl --location --request POST 'https://dev.azure.com/brunodeuner/teste/_apis/wit/workitems/$Task?api-version=7.0' \
            --header 'Content-Type: application/json-patch+json' \
            --header 'Authorization: Basic unbml4tuwcexawzao4zbqj37e6fwj7qjy4moa5iiazpjwvkfldqq' \
            --data-raw '[
                    {
                        "op": "add",
                        "path": "/fields/System.Title",
                        "from": null,
                        "value": "Code review ${{ github.event.pull_request.number }}"
                    },
                    {
                        "op": "add",
                        "path": "/fields/System.IterationPath",
                        "from": null,
                        "value": ${{ env.current_iteration }}
                    },
                    {
                        "op": "add",
                        "path": "/relations/-",
                        "value": {
                            "rel": "System.LinkTypes.Hierarchy-Reverse",
                            "url": "https://dev.azure.com/brunodeuner/teste/_workitems/edit/${{ env.work_item_id }}"
                        }
                    }
                ]'