name: Code review create on pull request opened

on:
  pull_request:
    types: [opened]

jobs:
  create-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Get actual PR number
        run: |
          echo "PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV 
      - name: Get actual iteration
        run: |
          echo "current_iteration=$(curl --location --request GET 'https://dev.azure.com/brunodeuner/teste/abc/_apis/work/teamsettings/iterations?$timeframe=current&api-version=7.0' \
            --header 'Authorization: Basic OjNtZ3F6d3Z2d2VuY2UycWtqNTVvbHFrNnlvY3NqNHpoc21lZDdodmx6cm12cXNqenIyZ3E=' | jq '.value[0].path')" >> $GITHUB_ENV 
      - name: Create task 
        run: |          
          curl --location --request POST 'https://dev.azure.com/brunodeuner/teste/_apis/wit/workitems/$Task?api-version=7.0' \
            --header 'Content-Type: application/json-patch+json' \
            --header 'Authorization: Basic OmpncnJodXNjc3FiNXN4NHFycjNqd2w1NnlncXVwYjd3dGpreGp2djV6N3g3M255ZnFvaGE=' \
            --data-raw '[
                    {
                        "op": "add",
                        "path": "/fields/System.Title",
                        "from": null,
                        "value": "Code review ${{ env.PR_NUMBER }}"
                    },
                    {
                        "op": "add",
                        "path": "/fields/System.IterationPath",
                        "from": null,
                        "value": "${{ env.current_iteration }}"
                    },
                    {
                        "op": "add",
                        "path": "/relations/-",
                        "value": {
                            "rel": "System.LinkTypes.Hierarchy-Reverse",
                            "url": "https://dev.azure.com/brunodeuner/_apis/wit/workItems/40"
                        }
                    }
                ]'