name: Code review create on pull request opened

on:
  pull_request:
    types: [opened]

jobs:
  create-code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
      - name: Get work_item_link
        run: |
          echo "work_item_link=$(${{ steps.PR.outputs.pr_body }} | grep "link_work_item" | grep -oE "[^/]+$")" >> $GITHUB_ENV 
      - name: Get iteration of work item
        run: |
          echo "current_iteration=$(curl --location --request GET 'https://dev.azure.com/brunodeuner/teste/_apis/wit/workitems/{{ env.work_item_link }}?api-version=7.0' \
            --header 'Authorization: Basic OmpncnJodXNjc3FiNXN4NHFycjNqd2w1NnlncXVwYjd3dGpreGp2djV6N3g3M255ZnFvaGE=' | jq '.fields."System.IterationPath"')" >> $GITHUB_ENV 
      - name: Create task 
        run: |          
          curl --location --request POST 'https://dev.azure.com/brunodeuner/teste/_apis/wit/workitems/$Task?api-version=7.0' \
            --header 'Content-Type: application/json-patch+json' \
            --header 'Authorization: Basic OmpncnJodXNjc3FiNXN4NHFycjNqd2w1NnlncXVwYjd3dGpreGp2djV6N3g3M255ZnFvaGE=' \
            --data-raw '[
                    {
                        "op": "add",
                        "path": "/fields/System.Title",
                        "from": null,
                        "value": "Code review ${{ steps.PR.outputs.number }}"
                    },
                    {
                        "op": "add",
                        "path": "/fields/System.IterationPath",
                        "from": null,
                        "value": ${{ env.current_iteration }}
                    },
                    {
                        "op": "add",
                        "path": "/relations/-",
                        "value": {
                            "rel": "System.LinkTypes.Hierarchy-Reverse",
                            "url": "${{ env.work_item_link }}"
                        }
                    }
                ]'